<%@ Page Title="" Language="C#" MasterPageFile="~/MasterCordinator.Master" AutoEventWireup="true" CodeBehind="NewSession.aspx.cs" Inherits="FinalFYP.New_Session" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <link rel="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="BootstrapFiles/css/bootstrap.css" rel="stylesheet" />
    <link href="BootstrapFiles/css/font-awesome.min.css" rel="stylesheet" />
    <link href="BootstrapFiles/css/style.css" rel="stylesheet" />


<%--<!--Header-->
     <div class="  text-white  "  style=" margin-left:20.90%;padding-top:2%;width:59% " >
   
    <header class="bg-primary py-2 text-white">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <h5><i class="fa fa-home"></i>MANAGE DEPARTMENT</h5>
                </div>
            </div>
        </div>
    </header>
         </div>
   
<!--NEW DEPARTMENT-->
    <section id="Section1" runat="server">
        <div class="container" runat="server">

            <div class="row" runat="server">
                <div class="col-md-4 ">
                    <div class="card ">
                        <div class="card-header">
                            <h3>Add Department</h3>
                        </div>

                        <div class="form-group">
                            <label for="title" class="form-control-label">Department</label>
                            <asp:TextBox ID="Tb_AddDepartment" runat="server" Height="40px" Width="99%" class="form-control" ></asp:TextBox>
                        </div>





                        <div class="modal-footer">
                            <asp:Button ID="BtnSave" runat="server" Text="Submit" class="btn btn-success" OnClick="BtnSave_Click" />
                            <button class="btn btn-primary">Update</button>
                        </div>
                        <asp:Label ID="DeptLabel" runat="server" Text="Label" Visible="False"></asp:Label>
                    </div>
                </div>

                <!--TABLE AREA-->
                <div class=" col-md-8" runat="server">
                    <div class="card-header ">
                        <h3>Depatrment Table</h3>
                    </div>
                    <div class="col-md-15" runat="server">
                        <asp:GridView ID="GridViewDept" runat="server"
                            AllowPaging="True" PageSize="3"
                            CssClass="table table-striped table-bordered table-hover"
                            OnPageIndexChanging="GridViewDept_PageIndexChanging"
                            AutoGenerateDeleteButton="True"
                            AutoGenerateSelectButton="True">
                        </asp:GridView>
                    </div>
                </div>
            </div>
        </div>
    </section>--%>





 <!--Header-->
    <div class="bg-info py-2 text-white" id="main-header">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <h5><i class="fa fa-home"></i>MANAGE PROGRAM</h5>
                </div>
            </div>
        </div>
    </div>
  
<!--Table-->
    <section id="posts" runat="server">
        <div class="container" runat="server">
            <div class="row" style= " margin-left:5%; margin-top:3%" runat="server">

                <!--Edit Foum-->
                <div class="col-md-4 ">
                    <div class="card ">
                        <div class="card-header">
                            <h3>Add Program</h3>
                        </div>

                         <asp:ScriptManager ID="Scrip1" runat="server"></asp:ScriptManager>
                           <asp:UpdatePanel ID="update1" runat="server"><ContentTemplate>
                           
                        <div class="form-group  " style="margin-left:9%">
                            <asp:TextBox ID="SesionID" runat="server" Visible="false"></asp:TextBox>
                                <label for="title" class="form-control-label ">Department</label>
                                <div>
                                    <asp:DropDownList ID="combo_Department" AutoPostBack="true" runat="server" AppendDataBoundItems="true"
                                        CssClass="mydropdownlist" Height="40px" Width="90%"  >
                                        <asp:ListItem Value="0" Text="--Select--"></asp:ListItem>
                                    </asp:DropDownList>
                                </div>
                            </div>

                        <div class="form-group" style="margin-left:9%">
                            <label for="title" class="form-control-label">Program</label>
                            <asp:TextBox ID="TextBox_program" runat="server" class="form-control" Height="40px" Width="90%" required="required"></asp:TextBox>

                        </div>
                        <asp:Label ID="LabelShow" runat="server" Text="Label" Visible="False"></asp:Label>
                               </ContentTemplate></asp:UpdatePanel>
                        <div class="modal-footer">
                            <asp:Button ID="btnsubmit" runat="server" Text="Submit" class="btn btn-success" OnClick="btnsubmit_Click" />
                            <asp:Button ID="btnUpdate" runat="server" Text="Update" class="btn btn-primary" OnClick="btnUpdate_Click" />
                           

                        </div>
                    </div>
                </div>




                <!--TABLE AREA-->
                <div class=" col-md-8" runat="server">
                   <%-- <div class="card-header ">
                        <h3>Session Table</h3>
                    </div>--%>
                    <div class="col-md-15" runat="server">
                         <asp:UpdatePanel ID="UpdatePanel2" runat="server"><ContentTemplate>
                        <asp:GridView ID="GridView_Session" runat="server"
                            AllowPaging="true" PageSize="5"
                            AutoGenerateDeleteButton="True"
                            AutoGenerateSelectButton="True"
                            DataKeyNames="ID"
                            CssClass="table table-striped table-bordered table-hover table-responsive"
                            OnPageIndexChanging="GridView_Session_PageIndexChanging" OnSelectedIndexChanged="GridView_Session_SelectedIndexChanged" OnRowDeleting="GridView_Session_RowDeleting">
                        </asp:GridView>
                             </ContentTemplate></asp:UpdatePanel>
                    </div>
                </div>



            </div>
        </div>
    </section>


</asp:Content>
