<%@ Page Title="" Language="C#" MasterPageFile="~/MasterCordinator.Master" AutoEventWireup="true" CodeBehind="Users.aspx.cs" Inherits="FinalFYP.Users" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    
     <link href="BootstrapFiles/css/bootstrap.css" rel="stylesheet" />
    <link href="BootstrapFiles/css/font-awesome.min.css" rel="stylesheet" />
    <link href="BootstrapFiles/css/style.css" rel="stylesheet" />


    <!--Header-->
<header class="bg-info py-2 text-white" id="main-header" >
<div class="container">
    <div class="row">
      <div class="col-md-9">
       <h5><i class="fa fa-home"></i>MANAGE USER'S</h5>
      </div>
    </div>
  </div>



</header>
 <!--Table & Edit Form-->
<section id="posts" >
<div class="container" >
 
    <div class="row  py-4   " >
    
         <!--Edit Foum-->
     <div class="col-md-4  "  >
        <div class="card Border " >
           <div class="card-header">
         <h3>Add User's</h3>
          </div>
         
            <section id="padding20" >
               
                <div class="form-group">
                    <asp:TextBox ID="tbUsers" runat="server" Visible="False"></asp:TextBox>
                </div>



                <asp:ScriptManager ID="Scrip1" runat="server"></asp:ScriptManager>
                           <asp:UpdatePanel ID="update1" runat="server"><ContentTemplate>
                
                <div class="form-group ContainerCenter " >
                    <asp:TextBox ID="tbUser" runat="server" Visible="False"></asp:TextBox>
                    <label for="title" class="form-control-label">User Type:</label>
                    <asp:DropDownList ID="combo_UserType" AutoPostBack="True" runat="server" AppendDataBoundItems="True"
                                CssClass="input100" Width="100%" Height="40px">
                                
                                <asp:ListItem>Teacher</asp:ListItem>
                                <asp:ListItem>Coordinator</asp:ListItem>
                            </asp:DropDownList>
                    <label for="title" class="form-control-label">User Name:</label>
                    <div style="margin-top: 0%">
                        <asp:TextBox ID="tbName" class="form-group " Width="99%" runat="server" CssClass="mydropdownlist " placeholder="user@suit" ></asp:TextBox>
                    </div>
                    <div style="margin-top: 0%">
                        <label for="title" class="form-control-label">Password:</label>
                        <asp:TextBox ID="tbPassword" class="form-group " Width="99%" runat="server" CssClass="mydropdownlist " placeholder="password"  ></asp:TextBox>
                    </div>
                </div>


                
</ContentTemplate></asp:UpdatePanel>
                <div class="modal-footer CustomBoxSetting  ContainerCenter ">
                    <asp:Button ID="btnsubmit" runat="server" Text="Submit" class="btn btn-success" OnClick="btnsubmit_Click"  />
                     <asp:Button ID="btnUpdate" runat="server" Text="Update" class="btn btn-primary" OnClick="btnUpdate_Click"  />
                </div>
                  
         </section>
          </div><!--card-->
      </div><!--col-md-4-->
      
    
    
    
  

            <!--TABLE AREA-->
        <div class=" col-md-8" runat="server">
          
        <div class="col-md-15" runat="server"> <asp:UpdatePanel ID="UpdatePanel2" runat="server"><ContentTemplate>
        <asp:GridView ID="GridView_User" runat="server" 
                      AllowPaging="true" PageSize="10"
                     DataKeyNames="ID"
                      AutoGenerateDeleteButton="True" 
                      AutoGenerateSelectButton="True"
                      CssClass="table table-striped table-bordered table-hover table-responsive"
                      OnPageIndexChanging="GridView_User_PageIndexChanging" OnRowDeleting="GridView_User_RowDeleting" OnSelectedIndexChanged="GridView_User_SelectedIndexChanged" >
            
        </asp:GridView>
            </ContentTemplate></asp:UpdatePanel>
         </div><!--col-md-15-->
         </div><!--TABLE AREA-->


     </div><!--row-->
   </div>  <!--container-->
</section>






</asp:Content>
